#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo
echo "================================"
echo " BusyBox initramfs booted"
echo "================================"
echo

exec /bin/sh